export const SITE_NAME = "Paulino Tech"
export const SITE_URL = "https://paulinotech.com"
export const SITE_TAGLINE = "IT meets security"
export const SITE_DESCRIPTION =
  "IT expert that builds secure infrastructure. Identity protection through account hardening and managed risk."

export interface NavLink {
  href: string
  label: string
}

/** Shown in the desktop header bar. Kept short enough to fit on one row. */
export const PRIMARY_NAV: readonly NavLink[] = [
  { href: "/experience", label: "Experience" },
  { href: "/deployments", label: "Deployments" },
  { href: "/homelab", label: "Home Lab" },
  { href: "/email-security", label: "Email Security" },
  { href: "/osint", label: "OSINT" },
  { href: "/ai-tooling", label: "AI Tooling" },
  { href: "/consulting", label: "Consulting" },
]

/** Everything the header bar cannot fit. Surfaced in the mobile menu and footer. */
export const SECONDARY_NAV: readonly NavLink[] = [
  { href: "/managed-os", label: "Managed OS" },
  { href: "/vendor-tooling", label: "Vendor Tooling" },
  { href: "/newsletter", label: "Newsletter" },
  { href: "/sitemap", label: "Sitemap" },
]

/** Home-page anchors. Absolute so they also work from a subpage. */
export const ANCHOR_NAV: readonly NavLink[] = [
  { href: "/#about", label: "About" },
  { href: "/#contact", label: "Contact" },
]

/** Grouped index rendered in the footer so every page is reachable from every page. */
export const FOOTER_SECTIONS: readonly { heading: string; links: readonly NavLink[] }[] = [
  {
    heading: "Infrastructure",
    links: [
      { href: "/experience", label: "Experience" },
      { href: "/deployments", label: "Deployments" },
      { href: "/homelab", label: "Home Lab" },
      { href: "/managed-os", label: "Managed OS" },
      { href: "/vendor-tooling", label: "Vendor Tooling" },
    ],
  },
  {
    heading: "Security",
    links: [
      { href: "/email-security", label: "Email Security" },
      { href: "/osint", label: "OSINT" },
      { href: "/consulting", label: "Consulting" },
      { href: "/ai-tooling", label: "AI Tooling" },
    ],
  },
  {
    heading: "More",
    links: [
      { href: "/#about", label: "About" },
      { href: "/newsletter", label: "Newsletter" },
      { href: "/sitemap", label: "Sitemap" },
      { href: "/#contact", label: "Contact" },
    ],
  },
]

/** Generated by `app/opengraph-image.tsx`. Referenced explicitly by pages that
 *  define their own `openGraph` block, since doing so replaces the inherited one. */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${SITE_NAME} — ${SITE_TAGLINE}`,
} as const
